on:
  push:
    paths-ignore:
      - "**/*.md"
env:
  JCP_VERSION: 2.0.40450-A
  JCP_FILENAME_PREFIX: jcp-
  DIADOC_SIGNING_SECRET: ${{ secrets.DIADOC_SIGNING_SECRET }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: 17
          maven-version: 3.9.8


      - name: Decrypt and Extract JCP Archive
        run: |
          openssl enc -d -aes-256-cbc \
            -in ./${{ env.JCP_FILENAME_PREFIX }}${{ env.JCP_VERSION }}.zip.enc \
            -out ./${{ env.JCP_FILENAME_PREFIX }}${{ env.JCP_VERSION }}.zip \
            -pass env:DIADOC_SIGNING_SECRET

          unzip -o ./${{ env.JCP_FILENAME_PREFIX }}${{ env.JCP_VERSION }}.zip 

      - name: Install JCP Dependencies
        run: |
          jars=(
            "JCP.jar ru.cryptopro jcp"
            "asn1rt.jar com.objsys.asn1j asn1rt"
            "ASN1P.jar ru.cryptopro asn1p"
            "JCryptoP.jar ru.cryptopro jcryptop"
          )

          for jar in "${jars[@]}"; do
            set -- $jar
            mvn install:install-file \
              -Dfile=./${{ env.JCP_FILENAME_PREFIX }}${{ env.JCP_VERSION }}/$1 \
              -DgroupId=$2 \
              -DartifactId=$3 \
              -Dversion=${{ env.JCP_VERSION }} \
              -Dpackaging=jar
          done

      - name: Run the build script
        run: mvn package
        env:
          github_ref_type: ${{ github.ref_type }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            target/*.jar
          if-no-files-found: error

      - name: Validate artifacts
        run: |
          VERSION_REGEX='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9][0-9]*|[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$'
          ARTIFACT_DIR=target
      
          for jar in $ARTIFACT_DIR/*.jar; do
            FILE_NAME=$(basename "$jar")
            if [[ ! "$FILE_NAME" =~ ^diadocsdk ]]; then
              echo "Skipping file $FILE_NAME: does not start with 'diadocsdk'"
              continue
            fi         
          
            VERSION=$(echo "$FILE_NAME" | grep -oP '(?<=diadocsdk-)[^-]+(?:-[^\.]+)?(?=\.jar)')
            if [[ -z "$VERSION" ]]; then
              echo "Error: Failed to extract version from $FILE_NAME"
              exit 1
            fi
      
            MATCH_RESULT=$(echo "$VERSION" | awk -v regex="$VERSION_REGEX" '
            BEGIN { result=1 }
            {
              if (match($0, regex)) {
                result=0
              } else {
                print "Error: Artifact " $0 " does not match the version regex " regex
              }
            }
            END { exit result }
            ')
            if [ $? -ne 0 ]; then
              echo "$MATCH_RESULT"
              exit 1
            fi
      
            echo "Artifact $FILE_NAME with version $VERSION matches the regex."
          done
      
          echo "All artifacts match the version regex."
  
  

  publish:
    runs-on: ubuntu-22.04
    needs: build
    if: |
      startsWith(github.event.ref, 'refs/tags/version')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate tag version
        run: |
          TAG="${{ github.ref }}"
          TAG="${TAG#refs/tags/}"
          echo "Extracted tag: ${TAG}"
          VERSION_REGEX='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9][0-9]*|[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$'
          MATCH_RESULT=$(echo "$TAG" | awk -v regex="$VERSION_REGEX" '
            BEGIN { result=1 }
            {
              if (match($0, regex)) {
              result=0
            } else {
              print "Error: Artifact " $0 " does not match the version regex " regex
            }
            }
            END { exit result }
            ')       
            if [ $? -ne 0 ]; then
              echo "$MATCH_RESULT"
              exit 1
            fi  

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages

      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          files: |
            **/*.jar